//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBartenderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMenu
    {
        public int OrderMenuId { get; set; }
        public string OrderName { get; set; }
        public int Quantity { get; set; }
        public string Drink { get; set; }
    }
}
